### ISSUE TITLE
Ping_device returns runtime error

### ISSUE THREAD

**Issue by pragnyakiri** [Srajdax/gnb#5]
On running Ping_Device function using curl -d {} http://localhost:32000/run/ping_device/1/60.60.0.101
We get HTTP Error 500 and runtime error in "forge.Ping" function call as below:
 runtime error: index out of range [0] with length 0
/usr/local/go/src/runtime/panic.go:88 (0x4325a2)
	goPanicIndex: panic(boundsError{x: int64(x), signed: true, y: y, code: boundsIndex})
/home/manoj20/free5gc/src/gnb/httpservice/api_ping.go:54 (0xa4203b)
	PingDevice: err = forge.Ping(device, helper.PDUSessionList[index])

We found that the PDUSessionList array is empty.
On digging further, we found that this array is not being populated when PDU session is being established (on running PDU session establish command).

In pdu_registration.go, in PDUSessionEstablishment function, the command "helper.PDUSessionList = append(helper.PDUSessionList, pduSession)" is not reachable during pduSessionEstablish command is being run (curl -d {} http://localhost:32000/run/establish_pdu/0
).

**Comment by manoj1919** [comment]
I have the same error!
even though curl -d {} http://localhost:32000/run/establish_pdu/0 returns success, helper.PDUSessionList is empty and ping using curl -d {} http://localhost:32000/run/ping_device/1/60.60.0.101 throws the runtime error.

**Comment by shynuu** [comment]
Hi @pragnyakiri  @manoj1919,

Sorry but this project is not maintained anymore.

Please use https://github.com/srajdax/free5gc-cli which is currently maintained and tested against compose and bare-metal version, help would be provided on free5gc-cli

I'm closing the issue.
