### ISSUE TITLE
Installation instructions while using free5gc-compose

### ISSUE THREAD

**Issue by manoj1919** [Srajdax/gnb#6]
Hi there,
I am new to GitHub, please excuse me if raising a new issue is not the way to ask for help.
In the readme file, it is said that this code is tested with free5gc compose 3.0.4. but all the instructions below are only to work with free5gc but not the compose version of it.
Can you please let me know how would I use your gNB with free5gc-compose?
Thanks
Manoj

**Comment by shynuu** [comment]
Hi @manoj1919,

Please refer to issue #5.

I'm closing the issue.
